### ISSUE TITLE
FIY: Homeassistant configuration

### ISSUE THREAD

**Issue by Finkregh** [davidkreidler/OpenCO2_Sensor#23]
I added this config to the `configuration.yml` of my homeassistant.

You can use https://www.uuidgenerator.net/version4 to generate your own individual IDs and assign an area in the UI after a reload.

```yaml
rest:
    scan_interval: 60
    resource: http://IPADDRESSorHOSTNAME:9925/
    method: GET
    sensor:
      - name: "NAME Co2"
        device_class: carbon_dioxide
        unique_id: "d611314f-9010-4d0d-aa3b-37c7f350c82f"
        value_template: >
            {{ value | regex_findall_index("(?:rco2.*})(\d+)") }}
      - name: "NAME Temperature"
        unique_id: "d611314f-9010-4d0d-aa3b-37c7f350c821"
        device_class: temperature
        value_template: >
            {{ value | regex_findall_index("(?:atmp.*})((?:\d|\.)+)") }}
      - name: "NAME Humidity"
        unique_id: "d611314f-9010-4d0d-aa3b-37c7f350c822"
        device_class: humidity
        value_template: >
            {{ value | regex_findall_index("(?:rhum.*})((?:\d|\.)+)") }}
```

Further documentation:
- https://www.home-assistant.io/integrations/rest/
- https://www.home-assistant.io/integrations/sensor.rest

Feel free to add it to the readme or where appropriate. Thanks for your work <3
